apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::675767036124:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::675767036124:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-190LTCDSWKTMD
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-15T17:35:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1427"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: a4582b7a-1963-4b19-b551-cb69a357a7e3
